// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE-O1eY0o-5i_U1ArlTanaA9cYgNbFxTc',
    appId: '1:335726003888:web:b57c30b0794abecde39d75',
    messagingSenderId: '335726003888',
    projectId: 'queue-apps-4e10b',
    authDomain: 'queue-apps-4e10b.firebaseapp.com',
    storageBucket: 'queue-apps-4e10b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRGDkPodsONcjfA5n3Go6SHex5V7Lt2XI',
    appId: '1:335726003888:android:4c75dc91100c4e45e39d75',
    messagingSenderId: '335726003888',
    projectId: 'queue-apps-4e10b',
    storageBucket: 'queue-apps-4e10b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-Y1i5LrJrWDicV59E7NDHCvgNU1mk2Q',
    appId: '1:335726003888:ios:6f2316d32b75900de39d75',
    messagingSenderId: '335726003888',
    projectId: 'queue-apps-4e10b',
    storageBucket: 'queue-apps-4e10b.appspot.com',
    iosBundleId: 'com.example.queueControlFlutter',
  );
}
